# redpanda-debezium.compose.yml
version: "3.9"
services:
  redpanda:
    image: vectorized/redpanda
    ports:
      - "9092:9092"
      - "39092:39092"
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - "1G"
      - --reserve-memory
      - "0M"
      - --node-id
      - "0"
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:39092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:39092,OUTSIDE://redpanda:9092
      - --check=false

  connect:
    image: debezium/connect
    depends_on:
      - redpanda
      - postgres
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: "redpanda:9092"
      GROUP_ID: "1"
      CONFIG_STORAGE_TOPIC: "inventory.configs"
      OFFSET_STORAGE_TOPIC: "inventory.offset"
      STATUS_STORAGE_TOPIC: "inventory.status"

  postgres:
    image: debezium/postgres:13
    ports:
      - 25432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d ch_benchmark_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ch_benchmark_db
      - PGPASSWORD=pw
    volumes:
      - .tpcc-benchmark/init:/docker-entrypoint-initdb.d
